package com.intelijake.mall.statistics.pojo.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Top selling product response DTO
 * Contains information about best performing products
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TopProductVO implements Serializable {
    
    private static final long serialVersionUID = 1L;
    
    /**
     * Product ID
     */
    @NotNull(message = "Product ID cannot be null")
    @Positive(message = "Product ID must be positive")
    private Integer productId;
    
    /**
     * Product name
     */
    @NotBlank(message = "Product name cannot be blank")
    private String productName;
    
    /**
     * Total quantity sold
     */
    @NotNull(message = "Total quantity cannot be null")
    private Long totalQuantity;
    
    /**
     * Total revenue generated by this product
     */
    @NotNull(message = "Total revenue cannot be null")
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    private BigDecimal totalRevenue;
}