spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234

  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        enabled: true
        ip: 127.0.0.1
        register-enabled: true
        namespace: public
        group: DEFAULT_GROUP
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000
  application:
    name: customer-service

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true

# Email Service Configuration
email:
  service:
    url: http://localhost:8084
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.intelijake.mall.pojo
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

server:
  port: 8084

# Management endpoints for monitoring and health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

# Circuit breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

# Logging configuration for debugging
logging:
  level:
    com.intelijake.mall.customer: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    com.netflix.hystrix: DEBUG

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION:eu-west-1}
    s3:
      bucket: ${AWS_S3_BUCKET:jake-mall-bucket}


